#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TennisMetrics.Droid.Resource", IsApplication=true)]

namespace TennisMetrics.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int games_array = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int sets_array = 2130771969;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020001
			public const int ace = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int aces = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int adCheck = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int bh = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int bhF = 2130837509;
			
			// aapt resource value: 0x7F02000A
			public const int bhfe = 2130837514;
			
			// aapt resource value: 0x7F020006
			public const int bhFE = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int bhStatsRow = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int bhUF = 2130837512;
			
			// aapt resource value: 0x7F02000B
			public const int bhuf = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int bhvF = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int bhvFE = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int bhvStatsRow = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int bhvUF = 2130837519;
			
			// aapt resource value: 0x7F020011
			public const int bhvw = 2130837521;
			
			// aapt resource value: 0x7F020010
			public const int bhvW = 2130837520;
			
			// aapt resource value: 0x7F020012
			public const int bhvwf = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int bhw = 2130837523;
			
			// aapt resource value: 0x7F020009
			public const int bhW = 2130837513;
			
			// aapt resource value: 0x7F020014
			public const int bhwf = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int df = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int dfs = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int error = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int fh = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int fhF = 2130837529;
			
			// aapt resource value: 0x7F02001F
			public const int fhfe = 2130837535;
			
			// aapt resource value: 0x7F02001A
			public const int fhFE = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int fhLabelRow = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int fhStatsRow = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int fhUF = 2130837533;
			
			// aapt resource value: 0x7F020020
			public const int fhuf = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int fhvF = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int fhvFE = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int fhvStatsRow = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int fhvUF = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int fhvW = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int fhvw = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int fhvwf = 2130837543;
			
			// aapt resource value: 0x7F02001E
			public const int fhW = 2130837534;
			
			// aapt resource value: 0x7F020028
			public const int fhw = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int fhwf = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int forced = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int forcedOppError = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int fragment = 2130837548;
			
			// aapt resource value: 0x7F02002E
			public const int fserve = 2130837550;
			
			// aapt resource value: 0x7F02002D
			public const int fsP = 2130837549;
			
			// aapt resource value: 0x7F02002F
			public const int gamesSpinner = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int groundstroke = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int isReturn = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int linearLayout1 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int mainMenu = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int mainMenuR = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int mainMenuStats = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int matchList = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int matchScore = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int menuButtonLayoutR = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int menuButtonLayoutS = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int oppName = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int oppRName = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int oppRRow = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int oppRScore = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int oppSRow = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int oppSScore = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int playerName = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int playerRName = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int playerRRow = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int playerRScore = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int playerSRow = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int playerSScore = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int prevMatch = 2130837574;
			
			// aapt resource value: 0x7F020048
			public const int returned = 2130837576;
			
			// aapt resource value: 0x7F020047
			public const int returnTable = 2130837575;
			
			// aapt resource value: 0x7F020049
			public const int serveRow = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int serveTable = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int setsSpinner = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int settingsNext = 2130837580;
			
			// aapt resource value: 0x7F02004E
			public const int sserve = 2130837582;
			
			// aapt resource value: 0x7F02004D
			public const int ssP = 2130837581;
			
			// aapt resource value: 0x7F02004F
			public const int startMatch = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int tbCheck = 2130837584;
			
			// aapt resource value: 0x7F020000
			public const int Title = 2130837504;
			
			// aapt resource value: 0x7F020051
			public const int unforced = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int unreturned = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int volley = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int winner = 2130837588;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Error = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ErrorTypeFragment = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ForcedError = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Point = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int PreviousMatches = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int Returned = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int Serve = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int Settings = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int SideFragment = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int StatsDisplay = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int StrokeFragment = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int Winner = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int game_prompt = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int set_prompt = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
