#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TennisMetrics.Droid.Resource", IsApplication=true)]

namespace TennisMetrics.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int games_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int sets_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int Title = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int ace = 2131099662;
			
			// aapt resource value: 0x7f06004b
			public const int aces = 2131099723;
			
			// aapt resource value: 0x7f06002c
			public const int adCheck = 2131099692;
			
			// aapt resource value: 0x7f060030
			public const int bh = 2131099696;
			
			// aapt resource value: 0x7f06003d
			public const int bhF = 2131099709;
			
			// aapt resource value: 0x7f06003b
			public const int bhFE = 2131099707;
			
			// aapt resource value: 0x7f060039
			public const int bhStatsRow = 2131099705;
			
			// aapt resource value: 0x7f06003c
			public const int bhUF = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int bhW = 2131099706;
			
			// aapt resource value: 0x7f060001
			public const int bhfe = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int bhuf = 2131099651;
			
			// aapt resource value: 0x7f060047
			public const int bhvF = 2131099719;
			
			// aapt resource value: 0x7f060045
			public const int bhvFE = 2131099717;
			
			// aapt resource value: 0x7f060043
			public const int bhvStatsRow = 2131099715;
			
			// aapt resource value: 0x7f060046
			public const int bhvUF = 2131099718;
			
			// aapt resource value: 0x7f060044
			public const int bhvW = 2131099716;
			
			// aapt resource value: 0x7f060053
			public const int bhvw = 2131099731;
			
			// aapt resource value: 0x7f060009
			public const int bhvwf = 2131099657;
			
			// aapt resource value: 0x7f060051
			public const int bhw = 2131099729;
			
			// aapt resource value: 0x7f060007
			public const int bhwf = 2131099655;
			
			// aapt resource value: 0x7f060027
			public const int df = 2131099687;
			
			// aapt resource value: 0x7f06004c
			public const int dfs = 2131099724;
			
			// aapt resource value: 0x7f060011
			public const int error = 2131099665;
			
			// aapt resource value: 0x7f060031
			public const int fh = 2131099697;
			
			// aapt resource value: 0x7f060038
			public const int fhF = 2131099704;
			
			// aapt resource value: 0x7f060036
			public const int fhFE = 2131099702;
			
			// aapt resource value: 0x7f060033
			public const int fhLabelRow = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int fhStatsRow = 2131099700;
			
			// aapt resource value: 0x7f060037
			public const int fhUF = 2131099703;
			
			// aapt resource value: 0x7f060035
			public const int fhW = 2131099701;
			
			// aapt resource value: 0x7f060000
			public const int fhfe = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int fhuf = 2131099650;
			
			// aapt resource value: 0x7f060042
			public const int fhvF = 2131099714;
			
			// aapt resource value: 0x7f060040
			public const int fhvFE = 2131099712;
			
			// aapt resource value: 0x7f06003e
			public const int fhvStatsRow = 2131099710;
			
			// aapt resource value: 0x7f060041
			public const int fhvUF = 2131099713;
			
			// aapt resource value: 0x7f06003f
			public const int fhvW = 2131099711;
			
			// aapt resource value: 0x7f060052
			public const int fhvw = 2131099730;
			
			// aapt resource value: 0x7f060008
			public const int fhvwf = 2131099656;
			
			// aapt resource value: 0x7f060050
			public const int fhw = 2131099728;
			
			// aapt resource value: 0x7f060006
			public const int fhwf = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int forced = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int forcedOppError = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int fragment = 2131099661;
			
			// aapt resource value: 0x7f060049
			public const int fsP = 2131099721;
			
			// aapt resource value: 0x7f060025
			public const int fserve = 2131099685;
			
			// aapt resource value: 0x7f06002e
			public const int gamesSpinner = 2131099694;
			
			// aapt resource value: 0x7f06004f
			public const int groundstroke = 2131099727;
			
			// aapt resource value: 0x7f060029
			public const int isReturn = 2131099689;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout1 = 2131099677;
			
			// aapt resource value: 0x7f06002a
			public const int mainMenu = 2131099690;
			
			// aapt resource value: 0x7f06001c
			public const int mainMenuR = 2131099676;
			
			// aapt resource value: 0x7f06004d
			public const int mainMenuStats = 2131099725;
			
			// aapt resource value: 0x7f060032
			public const int matchScore = 2131099698;
			
			// aapt resource value: 0x7f06001b
			public const int menuButtonLayoutR = 2131099675;
			
			// aapt resource value: 0x7f060028
			public const int menuButtonLayoutS = 2131099688;
			
			// aapt resource value: 0x7f060023
			public const int oppName = 2131099683;
			
			// aapt resource value: 0x7f060017
			public const int oppRName = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int oppRRow = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int oppRScore = 2131099672;
			
			// aapt resource value: 0x7f060022
			public const int oppSRow = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int oppSScore = 2131099684;
			
			// aapt resource value: 0x7f060020
			public const int playerName = 2131099680;
			
			// aapt resource value: 0x7f060014
			public const int playerRName = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int playerRRow = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int playerRScore = 2131099669;
			
			// aapt resource value: 0x7f06001f
			public const int playerSRow = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int playerSScore = 2131099681;
			
			// aapt resource value: 0x7f06000c
			public const int prevMatch = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int returnTable = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int returned = 2131099673;
			
			// aapt resource value: 0x7f060048
			public const int serveRow = 2131099720;
			
			// aapt resource value: 0x7f06001e
			public const int serveTable = 2131099678;
			
			// aapt resource value: 0x7f06002d
			public const int setsSpinner = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int settingsNext = 2131099695;
			
			// aapt resource value: 0x7f06004a
			public const int ssP = 2131099722;
			
			// aapt resource value: 0x7f060026
			public const int sserve = 2131099686;
			
			// aapt resource value: 0x7f06000b
			public const int startMatch = 2131099659;
			
			// aapt resource value: 0x7f06002b
			public const int tbCheck = 2131099691;
			
			// aapt resource value: 0x7f060005
			public const int unforced = 2131099653;
			
			// aapt resource value: 0x7f06001a
			public const int unreturned = 2131099674;
			
			// aapt resource value: 0x7f06004e
			public const int volley = 2131099726;
			
			// aapt resource value: 0x7f06000f
			public const int winner = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Error = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ErrorTypeFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ForcedError = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Point = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Returned = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Serve = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SideFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int StatsDisplay = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int StrokeFragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Winner = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int game_prompt = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int set_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
