#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TennisMetrics.Droid.Resource", IsApplication=true)]

namespace TennisMetrics.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000a
			public const int Title = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int ace = 2130968590;
			
			// aapt resource value: 0x7f04004a
			public const int aces = 2130968650;
			
			// aapt resource value: 0x7f04002c
			public const int adCheck = 2130968620;
			
			// aapt resource value: 0x7f040030
			public const int bh = 2130968624;
			
			// aapt resource value: 0x7f04003c
			public const int bhF = 2130968636;
			
			// aapt resource value: 0x7f04003a
			public const int bhFE = 2130968634;
			
			// aapt resource value: 0x7f040038
			public const int bhStatsRow = 2130968632;
			
			// aapt resource value: 0x7f04003b
			public const int bhUF = 2130968635;
			
			// aapt resource value: 0x7f040039
			public const int bhW = 2130968633;
			
			// aapt resource value: 0x7f040001
			public const int bhfe = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int bhuf = 2130968579;
			
			// aapt resource value: 0x7f040046
			public const int bhvF = 2130968646;
			
			// aapt resource value: 0x7f040044
			public const int bhvFE = 2130968644;
			
			// aapt resource value: 0x7f040042
			public const int bhvStatsRow = 2130968642;
			
			// aapt resource value: 0x7f040045
			public const int bhvUF = 2130968645;
			
			// aapt resource value: 0x7f040043
			public const int bhvW = 2130968643;
			
			// aapt resource value: 0x7f040052
			public const int bhvw = 2130968658;
			
			// aapt resource value: 0x7f040009
			public const int bhvwf = 2130968585;
			
			// aapt resource value: 0x7f040050
			public const int bhw = 2130968656;
			
			// aapt resource value: 0x7f040007
			public const int bhwf = 2130968583;
			
			// aapt resource value: 0x7f040027
			public const int df = 2130968615;
			
			// aapt resource value: 0x7f04004b
			public const int dfs = 2130968651;
			
			// aapt resource value: 0x7f040011
			public const int error = 2130968593;
			
			// aapt resource value: 0x7f040031
			public const int fh = 2130968625;
			
			// aapt resource value: 0x7f040037
			public const int fhF = 2130968631;
			
			// aapt resource value: 0x7f040035
			public const int fhFE = 2130968629;
			
			// aapt resource value: 0x7f040032
			public const int fhLabelRow = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int fhStatsRow = 2130968627;
			
			// aapt resource value: 0x7f040036
			public const int fhUF = 2130968630;
			
			// aapt resource value: 0x7f040034
			public const int fhW = 2130968628;
			
			// aapt resource value: 0x7f040000
			public const int fhfe = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int fhuf = 2130968578;
			
			// aapt resource value: 0x7f040041
			public const int fhvF = 2130968641;
			
			// aapt resource value: 0x7f04003f
			public const int fhvFE = 2130968639;
			
			// aapt resource value: 0x7f04003d
			public const int fhvStatsRow = 2130968637;
			
			// aapt resource value: 0x7f040040
			public const int fhvUF = 2130968640;
			
			// aapt resource value: 0x7f04003e
			public const int fhvW = 2130968638;
			
			// aapt resource value: 0x7f040051
			public const int fhvw = 2130968657;
			
			// aapt resource value: 0x7f040008
			public const int fhvwf = 2130968584;
			
			// aapt resource value: 0x7f04004f
			public const int fhw = 2130968655;
			
			// aapt resource value: 0x7f040006
			public const int fhwf = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int forced = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int forcedOppError = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int fragment = 2130968589;
			
			// aapt resource value: 0x7f040048
			public const int fsP = 2130968648;
			
			// aapt resource value: 0x7f040025
			public const int fserve = 2130968613;
			
			// aapt resource value: 0x7f04004e
			public const int groundstroke = 2130968654;
			
			// aapt resource value: 0x7f040029
			public const int isReturn = 2130968617;
			
			// aapt resource value: 0x7f04001d
			public const int linearLayout1 = 2130968605;
			
			// aapt resource value: 0x7f04002a
			public const int mainMenu = 2130968618;
			
			// aapt resource value: 0x7f04001c
			public const int mainMenuR = 2130968604;
			
			// aapt resource value: 0x7f04004c
			public const int mainMenuStats = 2130968652;
			
			// aapt resource value: 0x7f04001b
			public const int menuButtonLayoutR = 2130968603;
			
			// aapt resource value: 0x7f040028
			public const int menuButtonLayoutS = 2130968616;
			
			// aapt resource value: 0x7f04002d
			public const int numGames = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int numSets = 2130968622;
			
			// aapt resource value: 0x7f040023
			public const int oppName = 2130968611;
			
			// aapt resource value: 0x7f040017
			public const int oppRName = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int oppRRow = 2130968598;
			
			// aapt resource value: 0x7f040018
			public const int oppRScore = 2130968600;
			
			// aapt resource value: 0x7f040022
			public const int oppSRow = 2130968610;
			
			// aapt resource value: 0x7f040024
			public const int oppSScore = 2130968612;
			
			// aapt resource value: 0x7f040020
			public const int playerName = 2130968608;
			
			// aapt resource value: 0x7f040014
			public const int playerRName = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int playerRRow = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int playerRScore = 2130968597;
			
			// aapt resource value: 0x7f04001f
			public const int playerSRow = 2130968607;
			
			// aapt resource value: 0x7f040021
			public const int playerSScore = 2130968609;
			
			// aapt resource value: 0x7f04000c
			public const int prevMatch = 2130968588;
			
			// aapt resource value: 0x7f040012
			public const int returnTable = 2130968594;
			
			// aapt resource value: 0x7f040019
			public const int returned = 2130968601;
			
			// aapt resource value: 0x7f040047
			public const int serveRow = 2130968647;
			
			// aapt resource value: 0x7f04001e
			public const int serveTable = 2130968606;
			
			// aapt resource value: 0x7f04002f
			public const int settingsNext = 2130968623;
			
			// aapt resource value: 0x7f040049
			public const int ssP = 2130968649;
			
			// aapt resource value: 0x7f040026
			public const int sserve = 2130968614;
			
			// aapt resource value: 0x7f04000b
			public const int startMatch = 2130968587;
			
			// aapt resource value: 0x7f04002b
			public const int tbCheck = 2130968619;
			
			// aapt resource value: 0x7f040005
			public const int unforced = 2130968581;
			
			// aapt resource value: 0x7f04001a
			public const int unreturned = 2130968602;
			
			// aapt resource value: 0x7f04004d
			public const int volley = 2130968653;
			
			// aapt resource value: 0x7f04000f
			public const int winner = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Error = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ErrorTypeFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ForcedError = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Point = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Returned = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Serve = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SideFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int StatsDisplay = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int StrokeFragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Winner = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
	}
}
#pragma warning restore 1591
